name: Migration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd guest_house
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test all migrations
      run: |
        cd guest_house
        python3 manage.py makemigrations
        python3 manage.py migrate
